# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_trucker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucker',
            old_name='name',
            new_name='drivers_name',
        ),
        migrations.RenameField(
            model_name='trucker',
            old_name='product',
            new_name='state_of_product',
        ),
        migrations.RenameField(
            model_name='trucker',
            old_name='numbers',
            new_name='trucking_numbers',
        ),
    ]
